#This will trigger a the Build action to run on the Shift Left Demo
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ShiftLeft Protection
        run: |
          out=$(curl -H 'Authorization: token ${{secrets.PAT_TOKEN}}' https://api.github.com/repos/metalstormbass/ShiftLeft/contents/_build_flag | jq .sha)
          curl -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}"  -X PUT -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/metalstormbass/ShiftLeft/contents/_build_flag -d '{"message":"Building","content":${out}, "sha":${out}}'  
